### PR TITLE
fix: properly secret and unique AES key

### LINKED ISSUE #8: Auth key and iv should not be email
Randomly generate a `key` for each user upon signup. This key is then fetched from mongo at `/` and `/history`, used in the security file as the key. Keep IV as is

For the existing user use existing value

### PR DESCRIPTION
**Pull request by georgejmx**
Closes https://github.com/georgejmx/phantasos/issues/8

### CODE REVIEW

File: lib/security.ts [hunk 1]
```diff
@@ -1,23 +1,25 @@
...
+export function decryptText(hiddentext: string, email?: string | null, key?: string): string {
+    if (!email || !key) {
         throw Error("Unable to validate your credentials");
     }
-    const expandedEmail = email.repeat(6).slice(0, 32);
-    const userKey = crypto.enc.Hex.parse(expandedEmail);
-    const iv = crypto.enc.Hex.parse(reverseString(expandedEmail));
-    return crypto.AES.decrypt(hiddentext, userKey, { iv }).toString(crypto.enc.Utf8);
+    console.log(email);
+    console.log(key);
```
Comment (georgejmx) [inline lib/security.ts:22]: !!
